import = ["/home/kunheeha/.config/alacritty/rose.toml"]
live_config_reload = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "DMMonoNerdFont Medium"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 20
y = 16
